package Test;

import Domain.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import sun.org.mozilla.javascript.internal.ast.ForLoop;

/**
 *
 * @author Riboe
 */
public class TestFrame extends javax.swing.JFrame {

    private ArrayList<Product> products;
    private DefaultListModel model;
    private Controller control;
    private ArrayList<OrderDetail> newOrderDetails;
    private Product selectedProduct;
    private HashMap<Integer, Integer> mapProducts;
    private Employee selectedInstaller;
    private ArrayList<Employee> montører;
    private ArrayList<Installer> addedInstallers;
    
    public TestFrame() {
        initComponents();

        // Som sælger/kontorarbejder vil jeg kunne oprette en ordre på vegne af kunden, så vi ved hvad der skal leveres til kunden.
        control = new Controller();
        newOrderDetails = new ArrayList();
        products = control.getProducts();
        montører = new ArrayList();
        addedInstallers = new ArrayList();
        model = new DefaultListModel();
//        for (int i = 0; i < products.size(); i++) {
//            model.addElement(products.get(i));
//        }
//        listProducts.setModel(model);
            // Lav en Listener, der henter indexet af det valgte element.
        ListSelectionListener lsl = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                ListSelectionModel lsm = (ListSelectionModel) lse.getSource();
                int minIndex = lsm.getMinSelectionIndex();
                int maxIndex = lsm.getMaxSelectionIndex();
                for (int i = minIndex; i <= maxIndex; i++) {
                    if (lsm.isSelectedIndex(i)) {
                        listSelection(i);
                    }
                }
            }
        };
            // Føj listeneren til JListen.
        ListSelectionModel listSelectionModel = listProducts.getSelectionModel();
        listSelectionModel.addListSelectionListener(lsl);
        
        ListSelectionListener lslInstallers = new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent lse) {
                ListSelectionModel lsm = (ListSelectionModel) lse.getSource();
                int minIndex = lsm.getMinSelectionIndex();
                int maxIndex = lsm.getMaxSelectionIndex();
                for (int i = minIndex; i <= maxIndex; i++) {
                    if (lsm.isSelectedIndex(i)) {
                        listSelectionInstallers(i);
                    }
                }
            }
        };
            // Føj listeneren til JListen.
        ListSelectionModel listSelectionModelInstallers = listInstallers.getSelectionModel();
        listSelectionModelInstallers.addListSelectionListener(lslInstallers);
//        listSelection(0);
    }

    private void listSelectionInstallers(int index){
        selectedInstaller = montører.get(index);
    }
    
    private void listSelection(int index) {
        selectedProduct = products.get(index);
        labelItem.setText("Item: " + selectedProduct.getPnavn());
        labelAmount.setText("Amount: " + (selectedProduct.getAntalTotal() - mapProducts.get(selectedProduct.getpID())));
        labelPrice.setText("Price: " + selectedProduct.getPris());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listProducts = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSelected = new javax.swing.JList();
        labelItem = new javax.swing.JLabel();
        labelAmount = new javax.swing.JLabel();
        labelPrice = new javax.swing.JLabel();
        buttonAddToOrder = new javax.swing.JButton();
        buttonRemoveFromOrder = new javax.swing.JButton();
        buttonOpretOrdre = new javax.swing.JButton();
        tfAmount = new javax.swing.JTextField();
        tfFromDate = new javax.swing.JTextField();
        tfToDate = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        buttonOpretKunde = new javax.swing.JButton();
        tfEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfPhone = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        tfAdresse = new javax.swing.JTextField();
        tfZip = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfOrdrenr = new javax.swing.JTextField();
        buttonSøgOrdre = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        listInstallers = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        tfFromInstaller = new javax.swing.JTextField();
        tfToInstaller = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfTimeFrom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfTimeTo = new javax.swing.JTextField();
        buttonAddToOrderInstaller = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listInstallersAdded = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listProducts.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listProducts);

        listSelected.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listSelected);

        labelItem.setText("jLabel1");

        labelAmount.setText("jLabel1");

        labelPrice.setText("jLabel1");

        buttonAddToOrder.setText("Føj til ordre");
        buttonAddToOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddToOrderActionPerformed(evt);
            }
        });

        buttonRemoveFromOrder.setText("Fjern fra ordre");

        buttonOpretOrdre.setText("Opret Ordre");
        buttonOpretOrdre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpretOrdreActionPerformed(evt);
            }
        });

        tfAmount.setText("Mængde");

        tfFromDate.setText("Fra dato");
        tfFromDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfFromDateActionPerformed(evt);
            }
        });
        tfFromDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFromDateKeyReleased(evt);
            }
        });

        tfToDate.setText("Til Dato");

        buttonOpretKunde.setText("Opret kunde");
        buttonOpretKunde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpretKundeActionPerformed(evt);
            }
        });

        jLabel1.setText("Email");

        jLabel2.setText("Tlfnr.");

        jLabel3.setText("Navn");

        jLabel4.setText("Adresse");

        jLabel5.setText("Zip");

        jLabel6.setText("OPRET ORDRE");

        jLabel7.setText("OPRET KUNDE");

        jLabel8.setText("SØG EFTER ORDRE OG OPDATER IKKE FÆRDIG");

        jLabel9.setText("Ordrenr.");

        buttonSøgOrdre.setText("Søg");
        buttonSøgOrdre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSøgOrdreActionPerformed(evt);
            }
        });

        listInstallers.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(listInstallers);

        jLabel10.setText("Fra");

        tfFromInstaller.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfFromInstallerKeyReleased(evt);
            }
        });

        jLabel11.setText("Til");

        jLabel12.setText("Klokken");

        jLabel13.setText("-");

        buttonAddToOrderInstaller.setText("Føj til ordre");
        buttonAddToOrderInstaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddToOrderInstallerActionPerformed(evt);
            }
        });

        listInstallersAdded.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(listInstallersAdded);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(buttonAddToOrder, javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(buttonRemoveFromOrder, javax.swing.GroupLayout.Alignment.TRAILING)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(buttonOpretOrdre)))
                                        .addGap(167, 167, 167))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(labelItem)
                                            .addComponent(labelAmount)
                                            .addComponent(labelPrice))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(tfToDate)
                                            .addComponent(tfFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(98, 98, 98)))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfPhone))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfName)))
                                .addGap(78, 78, 78)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfZip, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(buttonOpretKunde)
                                        .addGap(98, 98, 98))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(61, 61, 61))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 740, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfOrdrenr, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(buttonSøgOrdre, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jSeparator3)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tfFromInstaller, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfToInstaller)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTimeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfTimeTo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonAddToOrderInstaller))
                        .addGap(58, 58, 58)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(buttonAddToOrder)
                                .addGap(18, 18, 18)
                                .addComponent(buttonRemoveFromOrder)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfFromDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addComponent(tfToDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelItem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelAmount)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPrice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonOpretOrdre)
                            .addComponent(tfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(tfAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tfZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonOpretKunde)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tfOrdrenr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonSøgOrdre))))
                .addGap(38, 38, 38)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tfFromInstaller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfToInstaller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(tfTimeFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(tfTimeTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(buttonAddToOrderInstaller))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfFromDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfFromDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfFromDateActionPerformed

    // Frederik
    private void buttonAddToOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddToOrderActionPerformed
        // TODO add your handling code here:
        int newAmount = selectedProduct.getAntalTotal() - Integer.parseInt(tfAmount.getText());
        int newRentedAmount = selectedProduct.getAntalUdlejet() + Integer.parseInt(tfAmount.getText());
        selectedProduct.setAntal(newAmount);
        selectedProduct.setAntalUdlejet(newRentedAmount);
        control.addDirtyProduct(selectedProduct);
        System.out.println("RET LINJEN NEDENUNDER - TestFrame - buttonAddToOrderActionPerformed -- DER SKAL IKKE STÅ \"-1\"");
        OrderDetail newOrderDetail = new OrderDetail(-1, selectedProduct.getpID(), Integer.parseInt(tfAmount.getText()));
        newOrderDetails.add(newOrderDetail);
        DefaultListModel m = new DefaultListModel();
        for (int i = 0; i < newOrderDetails.size(); i++) {
            m.addElement(newOrderDetails.get(i));
        }
        listSelected.setModel(m);
    }//GEN-LAST:event_buttonAddToOrderActionPerformed

    // Frederik
    private void buttonOpretOrdreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpretOrdreActionPerformed
        // TODO add your handling code here:
        System.out.println("RET LINJEN NEDENUNDER - TestFrame - buttonOpretOrdreActionPerformed - CUSTOMER ID ER HARDCODED IND.");
        Order o = control.createOrder(1000, tfFromDate.getText(), tfToDate.getText());
        for (int i = 0; i < newOrderDetails.size(); i++) {
            OrderDetail od = newOrderDetails.get(i);
            control.addOrderDetail(od.getpID(), od.getQuantity());
        }
        for (int i = 0; i < addedInstallers.size(); i++) {
            Installer in = addedInstallers.get(i);
            control.addInstaller(in.geteID(), in.getFrom().toString(), in.getTo().toString());
        }
        control.saveOrder();
        newOrderDetails.clear();
        addedInstallers.clear();
        listSelected.setModel(new DefaultListModel());
    }//GEN-LAST:event_buttonOpretOrdreActionPerformed

    //Frederik
    private void tfFromDateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFromDateKeyReleased
        // TODO add your handling code here:
        String match = "\\d\\d-\\w\\w\\w-\\dd\\dd\\dd\\dd";
//        if(tfFromDate.getText().matches(match) && tfToDate.getText().matches(match)){
            System.out.println("DOING STUFF");
            mapProducts = new HashMap();
            System.out.println("RET LINJEN NEDENUNDER - TestFrame - fFromDateKeyReleased -- DATOEN ER HARDCODED IND.");
            ArrayList<Order> ol = control.getOrders("03-jan-2013", "28-feb-2013");
            for (int i = 0; i < ol.size(); i++) {
                System.out.println(ol.get(i).getOID() + ": " +ol.get(i).detailsToString());
            }
            products = control.getProducts();
            for (int i = 0; i < products.size(); i++) {
                mapProducts.put(products.get(i).getpID(), 0);
            }
            ArrayList<OrderDetail> odl;
            for (int i = 0; i < ol.size(); i++) {
                odl = ol.get(i).getOrderDetails();
                for (int j = 0; j < odl.size(); j++) {
                    int key = odl.get(j).getpID();
                    int amount = mapProducts.get(key) + odl.get(j).getQuantity();
                    mapProducts.put(key, amount);
                }
            }
            DefaultListModel mod = new DefaultListModel();
            for (int i = 0; i < products.size(); i++) {
            Product product = products.get(i);
                mod.addElement(product);
            }
            listProducts.setModel(mod);
//        }
    }//GEN-LAST:event_tfFromDateKeyReleased

    // Frederik
    private void buttonOpretKundeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpretKundeActionPerformed
        // TODO add your handling code here:
        String name = tfName.getText();
        String email = tfEmail.getText();
        String adresse = tfAdresse.getText();
        int number = Integer.parseInt(tfPhone.getText());
        int zip = Integer.parseInt(tfZip.getText());
        Customer customer = control.createCustomer(name, email, number, adresse, zip);
        if(customer != null){
            control.saveCustomer();
        }
    }//GEN-LAST:event_buttonOpretKundeActionPerformed

    private void buttonSøgOrdreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSøgOrdreActionPerformed
        // TODO add your handling code here:
        Order o = control.getOrder(Integer.parseInt(tfOrdrenr.getText()));
        System.out.println(o.getOID());
        System.out.println(o.detailsToString());
        System.out.println(o.installersToString());
        System.out.println(control.calcTotal(o));
    }//GEN-LAST:event_buttonSøgOrdreActionPerformed

    //Frederik
    private void tfFromInstallerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfFromInstallerKeyReleased
        // TODO add your handling code here:
        String match = "\\d\\d-\\w\\w\\w-\\dd\\dd\\dd\\dd";
//        if(tfFromDate.getText().matches(match) && tfToDate.getText().matches(match)){
            System.out.println("DOING STUFF22222222");
            montører = control.getMontører();
            System.out.println("RET LINJEN NEDENUNDER - TestFrame - tfFromInstallerKeyReleased -- DATOEN ER HARDCODED IND.");
            tfFromInstaller.setText("01-jan-2013");
            tfToInstaller.setText("01-jan-2013");
            tfTimeFrom.setText("10:30");
            tfTimeTo.setText("16:00");
            ArrayList<Installer> il = control.getInstallers(tfFromInstaller.getText() + " " + tfTimeFrom.getText(),
                    tfToInstaller.getText() + " " + tfTimeTo.getText());
            DefaultListModel mod = new DefaultListModel();
            boolean b = false;
            for (int i = 0; i < montører.size(); i++) {
                for (int j = 0; j < il.size(); j++) {
                    if(montører.get(i).geteID() == il.get(j).geteID()){
                        b = true;
                    }
                }
                if(!b){
                    mod.addElement(montører.get(i));
                }
                b = false;
            }
            listInstallers.setModel(mod);
//        }
    }//GEN-LAST:event_tfFromInstallerKeyReleased

    // Frederik
    private void buttonAddToOrderInstallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddToOrderInstallerActionPerformed
        System.out.println("RET LINJEN NEDENUNDER - TestFrame - buttonAddToOrderActionPerformed -- DER SKAL IKKE STÅ \"-1\"");
        String from = tfFromInstaller.getText() + " " + tfTimeFrom.getText();
        String to = tfToInstaller.getText() + " " + tfTimeTo.getText();
        Installer newInstaller = new Installer(-1, selectedInstaller.geteID(), from, to);
        addedInstallers.add(newInstaller);
        DefaultListModel m = new DefaultListModel();
        for (int i = 0; i < addedInstallers.size(); i++) {
            m.addElement(addedInstallers.get(i));
        }
        listInstallersAdded.setModel(m);
    }//GEN-LAST:event_buttonAddToOrderInstallerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddToOrder;
    private javax.swing.JButton buttonAddToOrderInstaller;
    private javax.swing.JButton buttonOpretKunde;
    private javax.swing.JButton buttonOpretOrdre;
    private javax.swing.JButton buttonRemoveFromOrder;
    private javax.swing.JButton buttonSøgOrdre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelAmount;
    private javax.swing.JLabel labelItem;
    private javax.swing.JLabel labelPrice;
    private javax.swing.JList listInstallers;
    private javax.swing.JList listInstallersAdded;
    private javax.swing.JList listProducts;
    private javax.swing.JList listSelected;
    private javax.swing.JTextField tfAdresse;
    private javax.swing.JTextField tfAmount;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFromDate;
    private javax.swing.JTextField tfFromInstaller;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfOrdrenr;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfTimeFrom;
    private javax.swing.JTextField tfTimeTo;
    private javax.swing.JTextField tfToDate;
    private javax.swing.JTextField tfToInstaller;
    private javax.swing.JTextField tfZip;
    // End of variables declaration//GEN-END:variables
}
